Linux_Lock_Install script pulls linux_lock code and installs depend.

diff --git a/Server_Code/bash/linux_lock_install b/Server_Code/bash/linux_lock_install
--- a/Server_Code/bash/linux_lock_install
+++ b/Server_Code/bash/linux_lock_install
@@ -9,73 +9,102 @@
 # Description:
 #
 # This script installed Node.JS MongoDB and populates MongoDB with collection
-# required for Linux Lock System.
+# required for Linux Lock System. It also pulls Linux Lock from the repository and runs the server.
 #
-
-
+#
+#
 # @author Anatoly Spektor
 
 source linux_lock.conf # PLEASE DO NOT MODIFY THIS LINE!!!!
 
 setup_dir=`pwd`
 
+#FORMATTING STRINGS
+green='\e[0;32m'
+endColor='\e[0m'
+red='\e[0;31m'
+
+
 #Fine distribution and install Mongo depending on distro
 distro=$(cat /etc/*-release |  grep "^ID=" | awk -F'=' '{print $2}')
 arch=$(uname -m)
 clear
-if [[ "$distro" = "fedora" ]]
- then	
-	#Installing Mongo Dependencies (like git)
-	echo "[Linux Lock] Installing dependencies.."
-	sudo yum -y install git-core scons gcc-c++ glibc-devel
-
-elif [[ $distro = "ubuntu" ]]
+#checks if user is connected to Internet
+if ping  -w 5 -c 1 yahoo.com >& /dev/null
  then
+
+  if [[ "$distro" = "fedora" ]]
+   then	
 	#Installing Mongo Dependencies (like git)
-	echo "[Linux Lock] Installing dependencies.."
-	sudo apt-get install git-core build-essential scons
-else
-	echo "[Linux Lock] At This point LinuxLock supports only Fedora and Ubuntu, please email to support@linuxlock.com to get more information" 2> /dev/null 
+	echo -e  "${green}[Linux Lock] Installing dependencies.. ${endColor}"
+	sudo yum -y install git-core scons gcc-c++ glibc-devel >/dev/null
+  elif [[ $distro = "ubuntu" ]]
+  then
+	#Installing Mongo Dependencies (like git)
+	echo -e  "${green}[Linux Lock] Installing dependencies.. ${endColor}"
+	sudo apt-get install git-core build-essential scons >/dev/null
+  else
+	echo -e "${red}[Linux Lock] At This point LinuxLock supports only Fedora and Ubuntu, please email to support@linuxlock.com to get more information ${endColor}" >&2 
 	exit 134
-fi
+ fi
 
-# Creating Linux_Lock Path
-mkdir  $LINUX_LOCK_PATH >/dev/null 2>&1; cd  $LINUX_LOCK_PATH >/dev/null 2>&1
-
-# Checking if MongoDB is alredy installed
-type mongo  >/dev/null 2>&1
-if [[ $? != 0 ]]
- then 
+ # Checking if MongoDB is alredy installed
+ type mongo  >/dev/null 2>&1
+ if [[ $? != 0 ]]
+  then 
 	#Installing MongoDB
 	git clone git://github.com/mongodb/mongo.git; 
 	cd mongo; git checkout r2.4.0; 
 	scons all;
  else 
-	echo "[Linux Lock] Good news! You already have mongo installed! [skipping installation]";
-fi
+	echo -e "${green}[Linux Lock] Good news! You already have mongo installed! [skipping installation]${endColor}"
+ fi
 
 # Checking if Node is already installed
-type node >/dev/null 2>&1
-if [[ $? != 0 ]]
- then 
+ type node >/dev/null 2>&1
+ if [[ $? != 0 ]]
+  then 
 	#Installing Node.js
 	git clone git://github.com/joyent/node.git;
 	cd node; ./configure;make; 
 	sudo make install
- else 
-	echo "[Linux Lock] Good news! You already have Node installed! [skipping installation]";
-fi
+  else 
+	echo -e "${green}[Linux Lock] Good news! You already have Node installed! [skipping installation]${endColor}"
+ fi
 
-echo "[Linux Lock] Populating Mongo Database with required collections..."
-cd $setup_dir
-chmod 775 mongo_setup;
-chmod 775 mongo_test;
 
-#Populating MongoDB
+ # Creating Linux_Lock Path
+ if [ -d "$LINUX_LOCK_PATH" ]
+  then
+	echo -e "${red}[Linux Lock] Error: IT seems you already have $LINUX_LOCK_PATH , please delete all it's content to continue new instalaltion and run this script again!${endColor}" >&2
+	exit 1515
+ fi
+
+ echo -e "${green}[Linux Lock] Populating Mongo Database with required collections...${endColor}"
+ cd $setup_dir
+ chmod 775 mongo_setup;
+ chmod 775 mongo_test;
+
+ #Populating MongoDB
 mongo < ./mongo_setup | ./mongo_test
 
-# CREATE BACKUP DIR
-mkdir $LL_BACKUP_PATH
+ mkdir  $LINUX_LOCK_PATH >/dev/null 2>&1; cd  $LINUX_LOCK_PATH >/dev/null 2>&1
 
+ #clone git repo
+ echo -e "${green}[Linux Lock] Getting Linux Lock source code...${endColor}"
+ git clone git@github.com:rawkamatic/LinuxLock.git .
 
-echo "[Linux Lock] Succesfull installation of Node, Mongo and all dependencies required for Linux Lock!"
+ #installing additional dependencies
+  echo -e "${green}[Linux Lock] Installing additional dependencies...${endColor}"
+ cd $LINUX_LOCK_PATH/Server_Code; npm install >/dev/null
+
+  # CREATE BACKUP DIR
+  mkdir $LL_BACKUP_DIR
+
+  cd $LINUX_LOCK_PATH/Server_Code
+  echo -e "${green}[Linux Lock] Succesfull installation of Node, Mongo, Linux Lock and all dependencies!${endColor}"
+    echo -e "[Linux Lock] Please type -  node server.js  - to start Linux Lock "
+ else
+	echo -e "${red}[Linux Lock] Please ensure that you have internet connection and try again!${endColor}" >&2
+	exit 4
+fi
