Install script now installes node and mongo and populates mongo from mongo_setup

diff --git a/Server_Code/bash/linux_lock_install b/Server_Code/bash/linux_lock_install
--- a/Server_Code/bash/linux_lock_install
+++ b/Server_Code/bash/linux_lock_install
@@ -8,43 +8,55 @@
 #  - drop db and collection and than recreate
 #  - put more dummy values
 
+setup_dir=`pwd`
+
 #Fine distribution and install Mongo depending on distro
 distro=$(cat /etc/*-release |  grep "^ID=" | awk -F'=' '{print $2}')
 arch=$(uname -m)
-
-# Make sure only root can run our script
-#if [ "$(id -u)" != "0" ]; then
-#   echo "This script must be run as root" 1>&2
-#   exit 1
-#fi
-# ...
-
-
-if [ "$distro" = "fedora" ]
+clear
+if [[ "$distro" = "fedora" ]]
  then	
 	#Installing Mongo Dependencies (like git)
-	sudo yum -y install git-core scons gcc-c++ glibc-devel 2>/dev/null
-else if [[ $distro = "ubuntu" ]]
-   then
+	echo "Installing dependencies.."
+	sudo yum -y install git-core scons gcc-c++ glibc-devel
+
+elif [[ $distro = "ubuntu" ]]
+ then
 	#Installing Mongo Dependencies (like git)
-	sudo apt-get install git-core build-essential scons 2> /dev/null
-else exit 134
+	echo "Installing dependencies.."
+	sudo apt-get install git-core build-essential scons
+else
+	echo "At This point LinuxLock supports only Fedora and Ubuntu, please email to support@linuxlock.com to get more information" 2> /dev/null 
+	exit 134
 fi
-		
-  if [ $? == "0" ]
-      then
-			#Installing Mongo
-			type mongo >/dev/null 2>&1 || { git clone git://github.com/mongodb/mongo.git; cd mongo; git checkout r2.4.0; scons all }
-			#Installing Node
-			type node >/dev/null 2>&1 || { git clone git://github.com/joyent/node.git; cd node; ./configure;make; sudo make install }
-			#Installing LinuxLock
-			mkdir ~/linux_lock; cd linux_lock
-			#Pseudocode
-				#Clone Repo (need to be public)
-				#go to Server do npm install
-				#do mongo setup and mongo_test
-				#allow user to do some congif
-	
-			
-		fi
-exit 0
+
+mkdir ~/LinuxLock >/dev/null 2>&1; cd ~/LinuxLock >/dev/null 2>&1
+
+type mongo  >/dev/null 2>&1
+if [[ $? != 0 ]]
+ then 
+	git clone git://github.com/mongodb/mongo.git; 
+	cd mongo; git checkout r2.4.0; 
+	scons all;
+ else 
+	echo "Good news! You already have mongo installed! [skipping installation]";
+fi
+
+type node >/dev/null 2>&1
+if [[ $? != 0 ]]
+ then 
+	git clone git://github.com/joyent/node.git;
+	cd node; ./configure;make; 
+	sudo make install
+ else 
+	echo "Good news! You already have Node installed! [skipping installation]";
+fi
+
+echo "Populating Mongo Database with required collections..."
+cd $setup_dir
+chmod 775 mongo_setup;
+chmod 775 mongo_test;
+mongo < ./mongo_setup | ./mongo_test
+
+
+echo "Succesfull installation of Node, Mongo and all dependencies required for Linux Lock!"
